### ISSUE TITLE
Roadmap for Serre-Green-Naghdi

### ISSUE THREAD

**Issue by ranocha** [JoshuaLampert/DispersiveShallowWater.jl#129]
- [ ] flat bathymetry with central operators: #127
- [ ] flat bathymetry with upwind operators
- [ ] variable bathymetry (mild-slope approximation and full system)
- [ ] hyperbolic approximation
- [ ] #126
